### ISSUE TITLE
npm v.1.0.0

### ISSUE THREAD

**Issue by sectore** [akoenig/gulp.plugin.zsh#7]
Awesome plugin!

Could you publish latest version (v.1.0.0) to npm, please? 

P.S. Just a typo at the [README](https://github.com/akoenig/gulp.plugin.zsh#manually) 
`source $HOME/zsh-extensions/gulp.plugin.zsh/gulp-autocompletion.zsh`
should be
`source $HOME/zsh-extensions/gulp.plugin.zsh/gulp.plugin.zsh` ;)

-Jens

**Comment by akoenig** [comment]
Yap, renamed the plugin. Therefore this little typo. :)

All done in `v1.0.1`.

-André
